# Security Policy

**PLEASE DON'T DISCLOSE SECURITY-RELATED ISSUES PUBLICLY.**

## Reporting a Vulnerability

If you discover a security vulnerability within this package, please send an email to Braunson Yager at braunson@geekybeaver.ca. All security vulnerabilities will be promptly addressed.